import type { Metadata } from 'next'
import { Inter, Kaushan_Script } from 'next/font/google'
import './globals.css'
import localFont from 'next/font/local'



const anonymousPro = localFont({ src: './AnonymousPro-Regular.ttf' })



const inter = Inter({ subsets: ['latin'] })






export const metadata: Metadata = {
  title: 'Rangel Koli',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
